/*
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 */

/**
 * Check this implementation against the cases generated by
 * `tools/gen_differential_cases.py`, line by line.
 *
 *     python3 tools/gen_differential_cases.py /tmp/cases
 *     npx tsx tools/differential.ts /tmp/cases/inputs.txt /tmp/cases/expected.txt
 *
 * The shared vectors pin a few dozen agreed answers; this pins thousands,
 * generated from the shapes the encoder's branches actually turn on.
 */
import { readFileSync } from "node:fs";
import { decode, encode } from "../src/index.js";

const [inputsPath, expectedPath] = process.argv.slice(2);
if (!inputsPath || !expectedPath) {
  console.error("usage: differential <inputs.txt> <expected.txt>");
  process.exit(2);
}

const inputs = readFileSync(inputsPath, "utf8").split("\n");
const expected = readFileSync(expectedPath, "utf8").split("\n");

let line = 0;
let mismatches = 0;
for (let i = 0; i < inputs.length && i < expected.length; i++) {
  const hex = inputs[i]!.trim();
  if (hex === "" && expected[i]!.trim() === "" && i === inputs.length - 1) break;
  line++;
  const data = new Uint8Array(hex.length / 2);
  for (let k = 0; k < data.length; k++) {
    data[k] = Number.parseInt(hex.slice(2 * k, 2 * k + 2), 16);
  }
  const got = encode(data);
  const want = expected[i]!;
  if (got !== want) {
    if (mismatches < 5) console.error(`line ${line}: got  ${got}\n              want ${want}`);
    mismatches++;
  }
  // The round trip too, so a case cannot pass by agreeing on garbage.
  const back = decode(got);
  if (back.length !== data.length || !back.every((b, k) => b === data[k])) {
    console.error(`line ${line}: round trip failed`);
    mismatches++;
  }
}

console.log(`checked ${line} cases, ${mismatches} mismatches`);
process.exit(mismatches > 0 ? 1 : 0);
